require('./global')
const EventHub = require('event-hub')
capsid.def('event-hub', EventHub)
require('../util/jquery')
require('../util/rx')
const Multiflip = require('multiflip')
capsid.def('multiflip', Multiflip)
require('multiflip-bubble')
require('@kt3k/puncher')
require('../ui/common/menu-button')
require('../ui/common/blocker')
require('arrowkeys')
require('swipe-event/swipe-event')
require('swipe-event/swipe-cross')
